### ISSUE TITLE
Error when running app with responsive_toolkit

### ISSUE THREAD

**Issue by marcelosilvaidp** [Calpoog/flutter_responsive#4]
Hi Calvin,

When I flutter run my app with the responsive_toolkit, I got the following error in the Debug Console:
`Error: unable to find directory entry in pubspec.yaml: /Users/marcelosilva/.pub-cache/hosted/pub.dev/responsive_toolkit-0.0.5/images/`

Despite the error above, the app runs without any problems and the plugin works fine.

It must be something in the plugin code that is referencing `/user_home_directory/.pub-cache/hosted/pub.dev/responsive_toolkit-0.0.5/images/`.

It's a minor issue, bug given the quality of your work, it's worth to check it out.

**Comment by Calpoog** [comment]
Excellent catch. Looks like I left some cruft in the pubspec. It may have been from before I pulled out the examples into a separate project. I'll get it fixed, thanks!

**Comment by ricardoboss** [comment]
Any idea when a fix is available? This is kinda annoying which is sad for such a nice package :D

Currently, my workaround is to run `flutter pub get` on its own.

Can I do something to fix this faster?

**Comment by Calpoog** [comment]
Hey all!

Thank you so much for reporting this. I got the fix in a few weeks back but various other life occurrences side tracked me – but the fix is in as well as one other minor improvement and some CI fixes. Will be publishing to pub.dev after closing this issue!
